steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${SHORT_SHA}', '.' ]

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${SHORT_SHA}' ]

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: [
      'gcloud', 'run', 'deploy', '${_SERVICE_NAME}', 
      '--image', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${SHORT_SHA}',
      '--platform', 'managed',
      '--region', '${_REGION}',
      '--allow-unauthenticated',
      '--set-env-vars', 'DB_USER=${_DB_USER},DB_PASS=${_DB_PASS},DB_NAME=${_DB_NAME},DB_HOST=${_DB_HOST},INSTANCE_CONNECTION_NAME=${_INSTANCE_CONNECTION_NAME},GCS_BUCKET_NAME=${_GCS_BUCKET_NAME},QUEUE_NAME=${_QUEUE_NAME},ENV=deployment,CLOUD_RUN_URL=${_CLOUD_RUN_URL},PROJECT_ID=${PROJECT_ID}'
    ]
substitutions:
  _REGION: 'your-region'
  _LOCATION: 'your-region'
  _REPOSITORY: 'your-repository-name'
  _IMAGE_NAME: 'your-image-name'
  _SERVICE_NAME: 'your-service-name'
  _DB_USER: 'your-db-user'
  _DB_PASS: 'your-db-password'
  _DB_NAME: 'your-db-name'
  _DB_HOST: 'your-db-host'
  _QUEUE_NAME: 'your-queue-name'
  _GCS_BUCKET_NAME: 'your-gcs-bucket-name'
  _PROJECT_ID: 'your-project-id'
  _INSTANCE_CONNECTION_NAME: 'your-instance-connection-name'
  _CLOUD_RUN_URL: 'your-cloud-run-url'

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:${SHORT_SHA}'
options:
  logging: CLOUD_LOGGING_ONLY
